DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);
CREATE TABLE score
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	user_id BIGINT(20) NOT NULL COMMENT 'user主键ID',
	avg_value INT(11) NULL DEFAULT NULL COMMENT '分数',
	PRIMARY KEY (id)
);